""" Layer names """
LAYER_BACKDROP = 'Backdrop'
LAYER_PLAYER = 'Player'
LAYER_WALL = 'Wall'
LAYER_CLOUD = 'Cloud'

LAYER_FIRST_VOICEOVER = 'FirstVoiceOver'
LAYER_RANDOM_VOICEOVER = 'RandomVoiceOver'

LAYERS_VOICEOVER = [
    LAYER_FIRST_VOICEOVER,
    LAYER_RANDOM_VOICEOVER
]
