""" Settings constants """

SETTINGS_DEFAULT_FULLSCREEN = True
SETTINGS_DEFAULT_VSYNC = True
SETTINGS_DEFAULT_SIZE = '1280x720'
SETTINGS_DEFAULT_ANTIALIASING = 4
SETTINGS_DEFAULT_CENTER_WINDOW = False
SETTINGS_DEFAULT_SHOW_LOGO = True
SETTINGS_DEFAULT_SHOW_FPS = False

SETTINGS_DEFAULT_DRAW_RATE = 200
SETTINGS_DEFAULT_UPDATE_RATE = 62

SETTINGS_DEFAULT_VOLUME_SOUND = 70
SETTINGS_DEFAULT_VOLUME_MUSIC = 100
SETTINGS_DEFAULT_VOLUME_SPEECH = 100
SETTINGS_DEFAULT_VOLUME_MASTER = 100

SETTINGS_SIZE_MINIUM = (1280, 720)
SETTINGS_ANTIALIASING_CHOICES = 0, 2, 4, 8, 16
