""" Settings constants """

SETTINGS_DEFAULT_FULLSCREEN = True
SETTINGS_DEFAULT_VSYNC = True
SETTINGS_DEFAULT_SIZE = '1280x720'
SETTINGS_DEFAULT_ANTIALIASING = 4
ANTIALIASING_CHOICES = 0, 2, 4, 8, 16
